In [ ]:
# Understanding & Cleaning the Dataset

In [ ]:
import pandas as pd
import numpy as np

In [4]:
jobs = pd.read_csv('../data/alldata.csv')
# Importing the dataset

In [ ]:
jobs.head()
# Checking the first few rows of the dataset

,position,company,description,reviews,location
0,Development Director,ALS TDI,Development Director\nALS Therapy Development ...,NaN,"Atlanta, GA 30301"
1,An Ostentatiously-Excitable Principal Research...,The Hexagon Lavish,"Job Description\n\n""The road that leads to acc...",NaN,"Atlanta, GA"
2,Data Scientist,Xpert Staffing,"Growing company located in the Atlanta, GA are...",NaN,"Atlanta, GA"
3,Data Analyst,Operation HOPE,DEPARTMENT: Program OperationsPOSITION LOCATIO...,44.0,"Atlanta, GA 30303"
4,Assistant Professor -TT - Signal Processing & ...,Emory University,DESCRIPTION\nThe Emory University Department o...,550.0,"Atlanta, GA"

In [ ]:
jobs.shape
# Checking the shape of the dataset- number of rows and columns

(6964, 5)

In [ ]:
jobs.info()
# Checking the data types of each column and non-null counts

<class 'pandas.DataFrame'>
RangeIndex: 6964 entries, 0 to 6963
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   position     6953 non-null   str
 1   company      6953 non-null   str
 2   description  6953 non-null   str
 3   reviews      5326 non-null   float64
 4   location     6953 non-null   str
dtypes: float64(1), str(4)
memory usage: 272.2 KB

In [ ]:
jobs.isnull().sum()
# How many missing values are there in each column?

position         11
company          11
description      11
reviews        1638
location         11
dtype: int64

In [ ]:
jobs[jobs["position"].isnull()]
# Checking the rows where the "position" column has missing values

     position company description  reviews location
302       NaN     NaN         NaN      NaN      NaN
331       NaN     NaN         NaN      NaN      NaN
466       NaN     NaN         NaN      NaN      NaN
482       NaN     NaN         NaN      NaN      NaN
3337      NaN     NaN         NaN      NaN      NaN
5014      NaN     NaN         NaN      NaN      NaN
5059      NaN     NaN         NaN      NaN      NaN
5103      NaN     NaN         NaN      NaN      NaN
5114      NaN     NaN         NaN      NaN      NaN
6093      NaN     NaN         NaN      NaN      NaN
6168      NaN     NaN         NaN      NaN      NaN

In [ ]:
jobs = jobs.dropna(how='all')
# Getting rid of rows where all values are missing

In [ ]:
jobs.shape
# Double-checking the shape of the dataset after dropping rows

(6953, 5)

In [ ]:
jobs['position'].value_counts().head(20)
# The most common job positions in the dataset

position
Data Scientist                         351
Senior Data Scientist                   96
Research Analyst                        64
Data Engineer                           60
Machine Learning Engineer               56
Lead Data Scientist                     31
Research Scientist                      30
Sr. Data Scientist                      28
Principal Data Scientist                24
Data Analyst                            22
Software Engineer                       22
Quantitative Analyst                    21
Scientist                               17
Product Manager                         17
Bioinformatics Scientist                16
Market Research Analyst                 15
Senior Software Engineer                14
Machine Learning Scientist              13
Software Engineer, Machine Learning     13
Senior Research Analyst                 12
Name: count, dtype: int64

In [20]:
jobs['location'].value_counts().head(20)
# The most common job locations in the dataset

location
Seattle, WA            563
New York, NY           508
Cambridge, MA          487
Boston, MA             454
San Francisco, CA      425
San Diego, CA          294
Chicago, IL            292
Boulder, CO            233
Washington, DC         230
Sunnyvale, CA          221
Mountain View, CA      199
Los Angeles, CA        187
Austin, TX             156
Atlanta, GA            147
Redmond, WA 98052      117
Cambridge, MA 02139     95
Seattle, WA 98109       95
New York, NY 10016      83
San Diego, CA 92121     71
Cambridge, MA 02142     64
Name: count, dtype: int64